name: Create and Push Docker container
on:
  push:
    branches: main
env:
  username: kromos1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: bun-deps-{{ hashFiles(**/bun.lockb)}}

      - run: bun i --frozen-lockfile

      - name: Lint App
        run: bun run lint

      - name: Run Tests
        run: bun run test

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kromos1/${{ github.repository }}:1.0.0
